plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\kamil\\OneDrive\\Bureau\\claude\\Formation Yassine Sdiri\\jarvis-starter-kit\\livrables\\site-web"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]